const List<Map<String, String>> HOSPITAL_LIST = [
  {"name": "a. de la cruz maternity hospital"},
  {"name": "a. zarate general hospital"},
  {"name": "a.m. yumena general hospital inc."},
  {"name": "aacuacor health care & hospital"},
  {"name": "abella midway hospital"},
  {"name": "aborlan medical hospital"},
  {"name": "abpi-samama medical lying in clinic and hospital"},
  {"name": "abra de ilog municipal hospital"},
  {"name": "abra provincial hospital"},
  {"name": "abuyog district hospital"},
  {"name": "acebedo general hospital"},
  {"name": "adela serra ty memorial medical center"},
  {"name": "advent children's healthcare hospital"},
  {"name": "adventist hospital calbayog inc"},
  {"name": "adventist hospital-cebu, inc."},
  {"name": "adventist hospital-davao, inc."},
  {"name": "adventist hospital-palawan, inc."},
  {"name": "adventist hospital-santiago city, inc."},
  {"name": "adventist medical center manila"},
  {"name": "adventist medical center-bacolod, inc."},
  {"name": "adventist medical center-iligan city, inc."},
  {"name": "adventist medical center-valencia city, inc."},
  {"name": "adventist university of the philippines health service"},
  {"name": "aglipay district hospital"},
  {"name": "ago general hospital"},
  {"name": "agoo family hospital"},
  {"name": "agoo medical clinic"},
  {"name": "aguas maternity and general hospital"},
  {"name": "aguinaldo people's hospital"},
  {"name": "agusan del norte provincial hospital"},
  {"name": "air force general hospital"},
  {"name": "airforce city hospital"},
  {"name": "aisah medical hospital"},
  {"name": "aklan baptist hospital"},
  {"name": "aklan cooperative mission hospital"},
  {"name": "alaba emergency clinic and hospital"},
  {"name": "alabang medical center"},
  {"name": "alabang medical clinic"},
  {"name": "alabang medical clinic - las piñas branch"},
  {"name": "alabang medical clinic - muntinlupa branch"},
  {"name": "alabat island district hospital"},
  {"name": "alamada provincial community hosp."},
  {"name": "alaminos doctors hospital, inc."},
  {"name": "albay doctors? hospital, inc."},
  {"name": "albino m. duran memorial hospital"},
  {"name": "albor district hospital"},
  {"name": "alcala municipal hospital"},
  {"name": "aleosan district hospital"},
  {"name": "alfonso g. llanos hospital, inc."},
  {"name": "alfonso ponce enrile memorial district hospital"},
  {"name": "alfonso specialist hospital"},
  {"name": "alfredo e. mara?on sr. memorial district hospital"},
  {"name": "alicia district hospital"},
  {"name": "allah valley medical specialists center, inc."},
  {"name": "allegiant regional care hospitals, inc.(new)"},
  {"name": "allen district hospital"},
  {"name": "allied care experts (ace) dumaguete doctors, inc."},
  {"name": "allied care experts (ace) medical center - bohol, inc."},
  {"name": "allied care experts (ace) medical center - tacloban, inc."},
  {"name": "allied care experts (ace) medical center ?baliwag, inc."},
  {"name": "allied care experts (ace) medical center valenzuela, inc."},
  {"name": "allied care experts (ace) medical center-baypointe, inc. (fo"},
  {"name": "allied care experts (ace) medical center-pateros, inc."},
  {"name": "allied care experts (ace) medical center-quezon city, inc."},
  {"name": "almora general hospital"},
  {"name": "altavas district hospital"},
  {"name": "alterado general hospital, inc."},
  {"name": "amai pakpak medical center"},
  {"name": "amancio-fernandez lying in and clinic"},
  {"name": "amang rodriguez memorial medical center"},
  {"name": "amio community primary hospital"},
  {"name": "amisola maternity and childrens hospital"},
  {"name": "amma jadsac district hospital"},
  {"name": "amoroso medical clinic"},
  {"name": "amosup seamen?s hospital cebu"},
  {"name": "anahawan district hospital"},
  {"name": "anda riverview medical center, inc."},
  {"name": "andot medical clinic"},
  {"name": "andres soriano memorial hospital cooperative"},
  {"name": "anecito t. pesante sr. memorial hospital co."},
  {"name": "angel salazar memorial general hospital"},
  {"name": "angeles medical center, inc."},
  {"name": "angeles university foundation medical center, inc."},
  {"name": "angono medics hospital, inc."},
  {"name": "ann francis mother and child hospital"},
  {"name": "antipas medical specialist hospital, inc."},
  {"name": "antipolo city hospital system annex iv-mambugan"},
  {"name": "antipolo city hospital system-cabading"},
  {"name": "antipolo city medical hospital"},
  {"name": "antipolo doctors hospital"},
  {"name": "antique medical center, inc."},
  {"name": "anulao st. michael med. clinic & hosp."},
  {"name": "apacible memorial district hospital"},
  {"name": "apalit doctors hospital inc."},
  {"name": "aparri provincial hospital"},
  {"name": "apayao cagayan medical center, inc."},
  {"name": "apayao district hospital"},
  {"name": "apayao provincial hospital"},
  {"name": "aquino medical specialists hospital, inc."},
  {"name": "arakan valley district hospital"},
  {"name": "arayat doctors hospital"},
  {"name": "arescom infirmary"},
  {"name": "army general hospital"},
  {"name": "army station hospital, 2nd infirmary division, philippine ar"},
  {"name": "arnaiz hospital"},
  {"name": "aroroy municipal hospital"},
  {"name": "arteche district hospital"},
  {"name": "aruelo general hospital"},
  {"name": "asccom medical center"},
  {"name": "asentista doctors hospital and laboratory"},
  {"name": "asia medic family hospital and medical center"},
  {"name": "asian hospital inc."},
  {"name": "asilo hospital"},
  {"name": "asingan community hospital"},
  {"name": "assumption specialty hospital and medical center, inc."},
  {"name": "asturias infirmary clinic"},
  {"name": "atok district hospital"},
  {"name": "auguis clinic & hospital"},
  {"name": "aurora community & emergency hospital"},
  {"name": "aurora memorial hospital"},
  {"name": "awuyon community municipal hospital (formerly:baganga infirm"},
  {"name": "babol general hospital"},
  {"name": "bacnotan district hospital"},
  {"name": "bacolod our lady of mercy specialty hospital"},
  {"name": "bacoor district hospital"},
  {"name": "bacoor doctors medical center"},
  {"name": "badian district hospital"},
  {"name": "bagac community and medicare hospital"},
  {"name": "baggao district hospital"},
  {"name": "bago city hospital"},
  {"name": "bagong cainta municipal hospital"},
  {"name": "baguio general hospital and medical center"},
  {"name": "baguio medical center"},
  {"name": "bailan district hospital"},
  {"name": "bais district hospital"},
  {"name": "balaoan district hospital"},
  {"name": "balayan bayview hospital and medical center"},
  {"name": "balibago polyclinic and hospital, inc."},
  {"name": "balindong municipal hospital"},
  {"name": "baliuag district hospital"},
  {"name": "ballesteros district hospital"},
  {"name": "balo-i provincial hospital"},
  {"name": "balud municipal hospital"},
  {"name": "bangued christian hospital"},
  {"name": "bangui district hospital"},
  {"name": "bantayan district hospital"},
  {"name": "barili district hospital"},
  {"name": "barlig district hospital"},
  {"name": "baron-yee hospital"},
  {"name": "barrios-businos medical clinic and hospital"},
  {"name": "basa airbase hospital"},
  {"name": "basey district hospital"},
  {"name": "basilan community hospital"},
  {"name": "basilan general hospital"},
  {"name": "bataan doctors hospital and medical center, inc."},
  {"name": "bataan general hospital and medical center"},
  {"name": "bataan peninsula medical center"},
  {"name": "bataan st. joseph hospital & medical center corp."},
  {"name": "bataan women's hospital, inc."},
  {"name": "batanes general hospital"},
  {"name": "batangas health care hospital, jesus of nazareth"},
  {"name": "batangas healthcare specialists medical center (new)"},
  {"name": "batangas medical center"},
  {"name": "batangas provincial hospital"},
  {"name": "bataraza district hospital"},
  {"name": "bato maternity & children's hospital"},
  {"name": "bauan doctors general hospital"},
  {"name": "bauan general hospital"},
  {"name": "bautista hospital"},
  {"name": "bayambang district hospital"},
  {"name": "bayawan district hospital"},
  {"name": "baybay doctors hospital"},
  {"name": "bayugan city doctors hospital"},
  {"name": "bayugan community hospital"},
  {"name": "bayugan jm yap sto. nino hospital"},
  {"name": "bbcss pediatric medical and surgical clinic"},
  {"name": "beato-cauilan hospital"},
  {"name": "bendijo hospital"},
  {"name": "benguet general hospital"},
  {"name": "berachah medical clinic"},
  {"name": "bermudez polyclinic hospital, inc"},
  {"name": "bernardino general hospital i"},
  {"name": "bernardino general hospital ii"},
  {"name": "besao district hospital"},
  {"name": "bethany hospital, inc."},
  {"name": "bethel baptist hospital, inc."},
  {"name": "bi?an doctors? hospital incorporated"},
  {"name": "bicol access health centrum"},
  {"name": "bicol medical center"},
  {"name": "bicol regional training and teaching hospital"},
  {"name": "bicol sanitarium"},
  {"name": "biliran provincial hospital"},
  {"name": "binakayan hospital and medical center, inc."},
  {"name": "binalbagan infirmary"},
  {"name": "binangonan lakeview hospital, inc."},
  {"name": "bindoy district hospital"},
  {"name": "birhen sa regla medical clinic and hospital"},
  {"name": "biri district hospital"},
  {"name": "bishop joseph regan memorial hospital (formerly christ the k"},
  {"name": "bislig district hospital"},
  {"name": "blancia hospital"},
  {"name": "blanco doctor's hospital, inc."},
  {"name": "blessed family doctors general hospital"},
  {"name": "blessed trinity maternity and medical hospital, inc."},
  {"name": "bogo-medellin medical center"},
  {"name": "bolinao community hospital"},
  {"name": "bondoc peninsula district hospital"},
  {"name": "bongabon district hospital"},
  {"name": "bongao doctors' hospital"},
  {"name": "bongcas holy child hospital"},
  {"name": "bontilao country hospital"},
  {"name": "bontoc general hospital"},
  {"name": "bontuyan medical hospital, inc."},
  {"name": "borbon general hospital, inc."},
  {"name": "borja family hospital corporation"},
  {"name": "borongan doctors hospital"},
  {"name": "brent hospital and colleges, inc."},
  {"name": "brigadier general benito n. ebuen air base hospital"},
  {"name": "brigino general hospital, inc."},
  {"name": "brokenshire integrated health ministries, inc."},
  {"name": "bucay municipal hospital"},
  {"name": "buda comm.health care center"},
  {"name": "buenavista emergency hospital"},
  {"name": "bugasong medicare community hospital"},
  {"name": "bukidnon provincial hospital - kalilangan"},
  {"name": "bukidnon provincial hospital - kibawe"},
  {"name": "bukidnon provincial hospital - malitbog"},
  {"name": "bukidnon provincial hospital - manolo fortich"},
  {"name": "bukidnon provincial hospital - san fernando"},
  {"name": "bukidnon provincial hospital - talakag"},
  {"name": "bukidnon provincial hospital-maramag"},
  {"name": "bukidnon provincial medical center-malaybalay city"},
  {"name": "bulacan medical center"},
  {"name": "bulacan medical mission group pharmacy and hospital - turo b"},
  {"name": "bulalacao community hospital"},
  {"name": "buluan district hospital"},
  {"name": "bumanglag specialty hospital"},
  {"name": "bunawan district hospital"},
  {"name": "bungabong-sanico medical clinic & maternity hospital"},
  {"name": "burauen district hospital"},
  {"name": "buruanga municipal hospital"},
  {"name": "bustos community hospital"},
  {"name": "butuan doctors? hospital and college, incorporated"},
  {"name": "butuan medical center"},
  {"name": "butuan puericulture center no. 394, inc."},
  {"name": "c and h medical and surgical clinic, inc."},
  {"name": "c.d.o. polymedic medical plaza, inc."},
  {"name": "c.p. reyes hospital"},
  {"name": "caba district hospital"},
  {"name": "cabadbaran district hospital"},
  {"name": "cabarles maternity (lying-in), medical and children's clinic"},
  {"name": "cabatuan family hospital, inc."},
  {"name": "cabiao general hospital, inc."},
  {"name": "cabredo general hospital"},
  {"name": "cadiz district hospital"},
  {"name": "cadulong hospital"},
  {"name": "cagayan de oro medical center, inc."},
  {"name": "cagayan de oro polymedic general hospital, inc."},
  {"name": "cagayan de tawi-tawi district hospital"},
  {"name": "cagayan valley medical center"},
  {"name": "cagraray district hospital"},
  {"name": "cainglet med. hospital, inc."},
  {"name": "calalang general hospital"},
  {"name": "calamba district hospital"},
  {"name": "calamba doctors? hospital"},
  {"name": "calamba medical center, inc."},
  {"name": "calape mother and child hospital"},
  {"name": "calatagan medicare hospital"},
  {"name": "calatrava municipal hospital"},
  {"name": "calauag municipal hospital"},
  {"name": "calauag st. peter general hospital"},
  {"name": "calayan infirmary"},
  {"name": "calbayog district hospital"},
  {"name": "callang general hospital and medical center, inc."},
  {"name": "callejo medical clinic"},
  {"name": "caloocan city medical center"},
  {"name": "caloocan city north medical center"},
  {"name": "calumpit district hospital"},
  {"name": "camarines norte provincial hospital"},
  {"name": "camiguin general hospital"},
  {"name": "camp aquino station hospital"},
  {"name": "camp bado dangwa hospital"},
  {"name": "camp brig. gen. salipadala k pendatun hospital"},
  {"name": "camp elias angeles station hospital"},
  {"name": "camp evangelista station hospital"},
  {"name": "camp general artemio ricarte station hospital"},
  {"name": "camp general emilio aguinaldo station hospital"},
  {"name": "camp lapulapu station hospital, centcom, afp"},
  {"name": "camp lukban station hospital"},
  {"name": "camp melchor f. dela cruz station hospital"},
  {"name": "camp nakar station hospital"},
  {"name": "camp navarro general hospital"},
  {"name": "camp panacan station hospital"},
  {"name": "camp peralta station hospital"},
  {"name": "camp quintin m merecido hospital"},
  {"name": "can-avid municipal hospital"},
  {"name": "candaba municipal infirmary"},
  {"name": "candelaria district hospital"},
  {"name": "candelaria municipal hospital"},
  {"name": "candijay community hospital"},
  {"name": "candon general hospital"},
  {"name": "candon st. martin de porres hospital"},
  {"name": "canlaon district hospital"},
  {"name": "capalonga medicare and community hospital"},
  {"name": "capas medical center"},
  {"name": "capitol medical center, inc."},
  {"name": "capitol university medical center foundation of cagayan, inc"},
  {"name": "capiz doctor's hospital"},
  {"name": "capiz emmanuel hospital, inc."},
  {"name": "capul district hospital"},
  {"name": "caraga hospital infant care & lying-in center"},
  {"name": "caraga regional hospital"},
  {"name": "caramoan municipal hospital"},
  {"name": "caramoran municipal hospital"},
  {"name": "carcar women and children polyclinic and lying-in clinic"},
  {"name": "cardinal santos medical center"},
  {"name": "carigara district hospital"},
  {"name": "carlos medical and maternity hospital"},
  {"name": "carlos p. acosta clinic & hospital"},
  {"name": "carmen copper corporation hospital"},
  {"name": "carmen medical clinic & hospital"},
  {"name": "carmen municipal hospital"},
  {"name": "carmona hospital and medical center inc."},
  {"name": "carranglan medicare and community hospital"},
  {"name": "carrascal primary health care infirmary"},
  {"name": "carsigma district hospital"},
  {"name": "casimiro a. ynares sr. memorial hospital"},
  {"name": "castillon-gaurana general hospital (formerly lebak doctors h"},
  {"name": "castro maternity hospital and medical center, inc."},
  {"name": "cataingan district hospital"},
  {"name": "catanduanes doctors hospital, inc."},
  {"name": "catarman district hospital"},
  {"name": "catarman doctors hospital inc"},
  {"name": "catbalogan doctors hospital"},
  {"name": "catigbian district hospital"},
  {"name": "catubig district hospital"},
  {"name": "cauayan district hospital"},
  {"name": "cauayan family hospital"},
  {"name": "cauayan medical specialists hospital"},
  {"name": "cavite medical center"},
  {"name": "cavite municipal hospital"},
  {"name": "cavite naval hospital"},
  {"name": "cawayan municipal hospital"},
  {"name": "cebu (velez) general hospital, inc."},
  {"name": "cebu city medical center"},
  {"name": "cebu doctors? university hospital inc. (formerly cebu doctor"},
  {"name": "cebu north general hospital, inc."},
  {"name": "cebu provincial hospital (balamban)"},
  {"name": "cebu provincial hospital (bogo city)"},
  {"name": "cebu provincial hospital (carcar city)"},
  {"name": "cebu provincial hospital (danao city)"},
  {"name": "cebu puericulture center and maternity hospital"},
  {"name": "cebu south general hospital, inc."},
  {"name": "cem medical specialist hospital"},
  {"name": "centeno med. specialists hosp.inc."},
  {"name": "central azucarrera don pedro hospital"},
  {"name": "central luzon doctors? hospital, inc."},
  {"name": "central luzon state university hospital"},
  {"name": "central mindanao university hospital"},
  {"name": "centro medico de santisimo rosario, inc."},
  {"name": "cereville medical clinic and hospital"},
  {"name": "chacon general hospital, inc."},
  {"name": "charles w. selby memorial hosp., inc."},
  {"name": "chavez medical clinic"},
  {"name": "chinese general hospital & medical center"},
  {"name": "chong hua hospital"},
  {"name": "chong hua hospital mandaue (formerly chong hua hospital mand"},
  {"name": "christ the healer hospital"},
  {"name": "christ the king medical center unihealth las piñas, inc."},
  {"name": "christ the saviour general hospital, inc."},
  {"name": "christian general hospital"},
  {"name": "cicosat hospital"},
  {"name": "ciriaco s. tirol hospital"},
  {"name": "city medic emergency hospital corp."},
  {"name": "city of candon hospital"},
  {"name": "city of general trias doctors medical center inc. (formerly:"},
  {"name": "city of imus doctors hospital, inc."},
  {"name": "ciudad medical zamboanga"},
  {"name": "clarin community hospital"},
  {"name": "claro m. recto memorial district hospital"},
  {"name": "claveria district hospital"},
  {"name": "clinica antipolo hospital and wellness center, inc."},
  {"name": "clinica gatchalian & hospital"},
  {"name": "clinica isaguirre"},
  {"name": "clinica jesus nazareno"},
  {"name": "clinica luntao , inc. norala"},
  {"name": "clinica luntao , inc. santo nino"},
  {"name": "clinica ozaraga doctors hospital"},
  {"name": "codilla-ramos clinic and hospital"},
  {"name": "commonwealth hospital and medical center"},
  {"name": "community general hospital of san pablo city, inc."},
  {"name": "compostela valley provincial hospital - laak"},
  {"name": "compostela valley provincial hospital - montevista"},
  {"name": "compostela valley provincial hospital - pantukan"},
  {"name": "compostela valley provincial hospital -maragusan"},
  {"name": "concepcion district hospital"},
  {"name": "cong. lamberto l. macias memorial hospital"},
  {"name": "cong. simeon g. toribio memorial hospital"},
  {"name": "congressman enrique \"henry\" m. cojuangco memorial district h"},
  {"name": "congressman natalio p. castillo senior memorial hospital"},
  {"name": "conner district hospital"},
  {"name": "consuelo k. tan mem. medical center, inc."},
  {"name": "corado medical clinic and hospital"},
  {"name": "corazon c. aquino memorial hospital"},
  {"name": "corazon locsin montelibano memorial regional hospital"},
  {"name": "cordillera hospital of the divine grace inc."},
  {"name": "coron district hospital"},
  {"name": "corpuz clinic and hospital"},
  {"name": "corrompido specialty hospital"},
  {"name": "cortes municipal hospital"},
  {"name": "cotabato medical specialist hospital"},
  {"name": "cotabato provincial hospital"},
  {"name": "cotabato puericulture center and general hospital foundation"},
  {"name": "cotabato regional and medical center"},
  {"name": "crisostomo general hospital"},
  {"name": "crisostomo san juan medical clinic"},
  {"name": "crispin m. paragas memorial hospital (curuan)"},
  {"name": "cruz-dalida maternity hospital, inc."},
  {"name": "cruz-rabe maternity and general hospital"},
  {"name": "cruzado medical hospital"},
  {"name": "cuison hospital, inc."},
  {"name": "culasi district hospital"},
  {"name": "culion sanitarium and general hospital"},
  {"name": "cure philippines, inc."},
  {"name": "cuyo district hospital"},
  {"name": "d.o. plaza memorial hospital"},
  {"name": "d.t. protacio hospital"},
  {"name": "daanbantayan district hospital"},
  {"name": "daet doctors hospital incorporated"},
  {"name": "dagupan doctors villaflor memorial hospital, inc."},
  {"name": "dalapo-rudinas medical clinic"},
  {"name": "danao mother and child hospital"},
  {"name": "danao-sale hospital"},
  {"name": "daniel o. mercado medical center"},
  {"name": "daraga doctors hospital"},
  {"name": "dasmariñas city medical center, inc."},
  {"name": "dasol community hospital"},
  {"name": "datu alawadin bandon sr. memorial hospital"},
  {"name": "datu blah t. sinsuat district hospital"},
  {"name": "datu halun sakilan memorial hospital"},
  {"name": "davao del norte hospital ( carmen zone)"},
  {"name": "davao del norte hospital (isalnd garden city of samal zone)"},
  {"name": "davao del norte hospital (kapalong  zone)"},
  {"name": "davao del sur provincial hospital"},
  {"name": "davao doctors hospital"},
  {"name": "davao medical school foundation, inc."},
  {"name": "davao mediquest hospital, inc."},
  {"name": "davao oriental prov'l hosp- gov. generoso"},
  {"name": "davao oriental provincial medical center"},
  {"name": "davao regional medical center"},
  {"name": "davao regional medical center  ward extension (infirmary)"},
  {"name": "davo oriental prov'l hosp.-cateel"},
  {"name": "dawis community primary hospital"},
  {"name": "dayos-pascual medical clinic"},
  {"name": "de castro hospital foundation, inc."},
  {"name": "de jesus general hospital"},
  {"name": "de la salle university medical center"},
  {"name": "de los reyes medical clinic"},
  {"name": "de los santos medical center"},
  {"name": "de ocampo memorial medical center"},
  {"name": "de vera medical center, inc."},
  {"name": "decena general hospital"},
  {"name": "deiparine community hospital"},
  {"name": "del carmen medical clinic and hospital"},
  {"name": "dela cerna medical clinic"},
  {"name": "delbert jon's polyclinic incorporated"},
  {"name": "delfin albano community hospital"},
  {"name": "delly delfin lorca health care"},
  {"name": "demano's medical and pediatric clinic"},
  {"name": "dennis molintas district hospital"},
  {"name": "deseret surgimed hospital"},
  {"name": "detecio community hospital"},
  {"name": "diadi emergency hospital"},
  {"name": "diffun district hospital"},
  {"name": "dignum foundation hospital, inc."},
  {"name": "digos doctors? hospital, inc."},
  {"name": "diliman doctors hospital, inc. (new)"},
  {"name": "dinagat district hospital"},
  {"name": "dinaig municipal hospital"},
  {"name": "dingras district hospital"},
  {"name": "diocesan medical foundation of san antonio de padua, inc."},
  {"name": "diones hospital"},
  {"name": "dionisio m. cornel medical center, inc."},
  {"name": "diosdado p. macapagal memorial hospital"},
  {"name": "divine care hospital multi services corp."},
  {"name": "divine grace medical center"},
  {"name": "divine heart medical service and development cooperative hos"},
  {"name": "divine love general hospital"},
  {"name": "divine mercy foundation of urdaneta hospital"},
  {"name": "divine mercy hospital"},
  {"name": "divine mercy hospital, inc."},
  {"name": "divine mercy wellness center, inc."},
  {"name": "divine providence infirmary and diagnostic center"},
  {"name": "divine word hospital"},
  {"name": "dizon hospital and medical center"},
  {"name": "dls-dr. rodolfo r. poblete memorial hospital"},
  {"name": "do?a remedios trinidad-romualdez medical foundation, inc. (f"},
  {"name": "doctors community hospital"},
  {"name": "dolores medicare and community hospital"},
  {"name": "domingo b. flores district hospital"},
  {"name": "domingo casano hospital"},
  {"name": "dominican hospital, inc."},
  {"name": "don carlos doctors hospital"},
  {"name": "don emilio del valle memorial hospital"},
  {"name": "don jose s. monfort medical center extension hospital"},
  {"name": "don leovigildo n. diapo, sr. municipal hospital"},
  {"name": "don manuel lopez memorial district hospital"},
  {"name": "don modesto formilleza sr. memorial hospital"},
  {"name": "don ramon tugbang medical center"},
  {"name": "don salvador benedicto memorial district hospital"},
  {"name": "don valerio palmares, sr. memorial district hospital"},
  {"name": "dona josefa e. marcos district hospital"},
  {"name": "dona maria d. tan memorial hospital"},
  {"name": "donsol district hospital"},
  {"name": "doña marta memorial district hospital"},
  {"name": "dr. a.p zantua memorial hospital"},
  {"name": "dr. abdullah hospital"},
  {"name": "dr. alberto m. pastor hospital"},
  {"name": "dr. amado b. diaz provincial hospital"},
  {"name": "dr. amando d. cope memorial hospital, inc."},
  {"name": "dr. amando l. garcia medical center, inc."},
  {"name": "dr. andres luciano jr. memorial hospital"},
  {"name": "dr. antonio a. ranada clinic and lying-in hospital"},
  {"name": "dr. apollo duque memorial hospital"},
  {"name": "dr. arturo p. pingoy medical center"},
  {"name": "dr. bernardo b. corral memorial hospital"},
  {"name": "dr. bonifacia v. albano memorial hospital"},
  {"name": "dr. cabuco hospital"},
  {"name": "dr. catalino gallego nava provincial hospital"},
  {"name": "dr. cornelio t. martinez sr. memorial hospital"},
  {"name": "dr. damian reyes provincial hospital"},
  {"name": "dr. domingo b. tamondong memorial hospital & college foundat"},
  {"name": "dr. domingo s. de leon general hospital"},
  {"name": "dr. eduardo v. roquero memorial hospital"},
  {"name": "dr. emigdio c. cruz sr. memorial hospital"},
  {"name": "dr. erlinda b. estanislao memorial hospital"},
  {"name": "dr. erlinda p. tolentino medical clinic and hospital"},
  {"name": "dr. ernesto h. malabanan memorial hospital"},
  {"name": "dr. ester r. garcia medical center, inc."},
  {"name": "dr. eutiquio ll. atanacio jr. memorial hospital"},
  {"name": "dr. fe del mundo medical center"},
  {"name": "dr. fernando b. duran, sr. memorial hospital"},
  {"name": "dr. florentino c. doble memorial hospital"},
  {"name": "dr. francisco c. parcon clinic & hospital"},
  {"name": "dr. gloria d. lacson general hospital"},
  {"name": "dr. gregorio b. tan memorial hospital"},
  {"name": "dr. gumersindo garcia sr memorial hospital"},
  {"name": "dr. henry m. de villa memorial hospital"},
  {"name": "dr. ignacio m. cortes general hospital, inc."},
  {"name": "dr. ildefonso alcantara memorial hospital"},
  {"name": "dr. jesus c. delgado memorial hospital"},
  {"name": "dr. john a. iglesia medical clinic"},
  {"name": "dr. jorge p. royeca hospital"},
  {"name": "dr. jose fabella memorial hospital"},
  {"name": "dr. jose ma. borromeo memorial hospital"},
  {"name": "dr. jose ma. torres mem. hospital inc."},
  {"name": "dr. jose n. rodriguez memorial hospital"},
  {"name": "dr. jose p. rizal memorial district hospital"},
  {"name": "dr. jose rizal district hospital"},
  {"name": "dr. jose rizal memorial hospital  (doh retained)"},
  {"name": "dr. joseph rey bacalso medical clinic & infirmary"},
  {"name": "dr. lim's clinic and hospital"},
  {"name": "dr. lorenzo b. principe clinic & drugstore, inc."},
  {"name": "dr. lorenzo t. ziga memorial district hospital"},
  {"name": "dr. manuel b. veloso memorial hospital"},
  {"name": "dr. marcelo m. chan memorial hospital, inc."},
  {"name": "dr. miguel v. alegre hospital"},
  {"name": "dr. montano g. ramos general hospital"},
  {"name": "dr. montano g. ramos general hospital corporation"},
  {"name": "dr. nilo o. roa memorial foundation hospital, inc."},
  {"name": "dr. pablo o. torre memorial hospital"},
  {"name": "dr. paulino j. garcia memorial research & medical center"},
  {"name": "dr. peralta hospital co."},
  {"name": "dr. petronilo v. seares sr. memorial hospital"},
  {"name": "dr. pjgmrmc talavera extension hospital"},
  {"name": "dr. r. rosales memorial medical hospital, inc."},
  {"name": "dr. r.a.m. albutra general hospital"},
  {"name": "dr. rafael s. tumbokon memorial hospital"},
  {"name": "dr. ramon b. gustilo hospital"},
  {"name": "dr. ramon pesante clinic and hospital, inc."},
  {"name": "dr. ricardo s. provido, sr. memorial district hospital"},
  {"name": "dr. ricardo y. ladrido memorial district hospital"},
  {"name": "dr. robosa hospital"},
  {"name": "dr. rogelio m. garcia memorial hospital"},
  {"name": "dr. roland p. dela cruz mem. hosp."},
  {"name": "dr. ronald p. guzman medical center, inc."},
  {"name": "dr. sabili health services corporation"},
  {"name": "dr. serapio b. montaner jr. al-haj memo. hospital"},
  {"name": "dr. sofronio b. garcia memorial hospital"},
  {"name": "dr. tomas l. nolasco  sr. memorial hospital - reproductive h"},
  {"name": "dr. tomas sr. and maria quilang medical and maternity clinic"},
  {"name": "dr. uy hospital, inc."},
  {"name": "dr. victor r. potenciano medical center"},
  {"name": "dr. victor s. villaroman memorial hospital"},
  {"name": "dr. wilfredo g. cortes hospital inc."},
  {"name": "dr. yanga's hospital, inc."},
  {"name": "drazen community hospital"},
  {"name": "duay hospital"},
  {"name": "dubongcos medical clinic"},
  {"name": "dumlao hospital"},
  {"name": "dupax district hospital"},
  {"name": "dvo. oriental prov'l hosp.- lupon"},
  {"name": "dvo. oriental prov'l. hosp-manay"},
  {"name": "e and r hospital and pharmacy"},
  {"name": "e. contreras medical clinic"},
  {"name": "e. zarate hospital"},
  {"name": "e.d. lim maternity and general hospital"},
  {"name": "e.s. garcia hospital"},
  {"name": "east avenue medical center"},
  {"name": "eastern bicol medical center"},
  {"name": "eastern laguna medical hospital"},
  {"name": "eastern pangasinan district hospital"},
  {"name": "eastern samar provincial hospital"},
  {"name": "eastern visayas regional medical center (new)"},
  {"name": "echague district hospital"},
  {"name": "ediborah p. yap memorial hospital"},
  {"name": "eduardo l. joson memorial hospital"},
  {"name": "edwin andrews airbase hospital"},
  {"name": "el corazon de jesus medical and diagnostic clinic"},
  {"name": "eleuterio t. decena memorial hospital"},
  {"name": "elguira general hospital"},
  {"name": "elvin u. masigan integrated memorial hospital"},
  {"name": "emil joanna general hospital"},
  {"name": "emilio aguinaldo college medical center cavite"},
  {"name": "emilio g. perez memorial hospital"},
  {"name": "emmanuel hospital"},
  {"name": "ermavi hospital"},
  {"name": "ernestoguadalupecomm.hospital"},
  {"name": "eros medical clinic"},
  {"name": "eros medical lying in clinic"},
  {"name": "escolastica romero district hospital"},
  {"name": "esperanza medicare community hospital"},
  {"name": "estacion med. clinic & hosp."},
  {"name": "estela medical clinic & pharmacy"},
  {"name": "estevez memorial hospital, inc."},
  {"name": "esther hospital"},
  {"name": "estrella hospital"},
  {"name": "evangelista medical clinic and hospital"},
  {"name": "evangelista medical specialty hospital, inc."},
  {"name": "eversley childs sanitarium"},
  {"name": "f.p. urbiztondo medical hospital inc."},
  {"name": "f.y. manalo medical foundation, inc."},
  {"name": "fabella-narciso medical and maternity clinic"},
  {"name": "fairview general hospital, inc."},
  {"name": "family care hospital, inc."},
  {"name": "family healthcare hospital-the reine-mere medical facilities"},
  {"name": "family medical clinic"},
  {"name": "far north luzon general hospital & training center"},
  {"name": "fatima university medical center antipolo corp. (new)"},
  {"name": "fatima university medical center corporation"},
  {"name": "fcc infirmary"},
  {"name": "federico roman tirador, sr. memorial district hospital"},
  {"name": "felipe abrigo memorial hospital"},
  {"name": "fernando air base hospital"},
  {"name": "feu - dr. nicanor reyes medical foundation, inc."},
  {"name": "first cabuyao hospital and medical center, inc. (new)"},
  {"name": "first filipino saint hospital"},
  {"name": "flora district hospital"},
  {"name": "flordeliz med. clin. & hosp."},
  {"name": "flores memorial medical center"},
  {"name": "floridablanca doctors? hospital, inc."},
  {"name": "fort del pilar station hospital"},
  {"name": "fort magsaysay army station hospital"},
  {"name": "foundation of our lady of peace mission, inc.-our lady of pe"},
  {"name": "fr. gerry filippetto memorial foundation hospital"},
  {"name": "fr. tulio favali municipal hospital"},
  {"name": "francisca apao uy memorial hospital"},
  {"name": "francisco dagohoy municipal hospital"},
  {"name": "franco clinic and hospital"},
  {"name": "gabaldon medicare and community hospital"},
  {"name": "galinato family clinic and hospital"},
  {"name": "gamay district hospital"},
  {"name": "gamay doctors hospital"},
  {"name": "gambalan hospital"},
  {"name": "gamez hospital"},
  {"name": "gandara district hospital"},
  {"name": "gaoat general hospital"},
  {"name": "gapan district hospital"},
  {"name": "garchitorena medicare community hospital"},
  {"name": "garcia general hospital"},
  {"name": "garcia memorial provincial hospital"},
  {"name": "gat andres bonifacio memorial medical center"},
  {"name": "gattaran emergency hospital"},
  {"name": "gen. macarthur municipal hospital"},
  {"name": "gen. miguel m. malvar medical foundation hospital"},
  {"name": "general emilio aguinaldo memorial hospital"},
  {"name": "general santos doctors? hospital, inc."},
  {"name": "general tinio medicare and community hospital"},
  {"name": "general trias maternity and pediatric hospital"},
  {"name": "general trias medicare hospital"},
  {"name": "generosa i. gonzales memorial hospital"},
  {"name": "gensan medical center"},
  {"name": "gentri medical center and hospital, inc."},
  {"name": "gerona hospital of the sacred heart"},
  {"name": "gertes clinic and hospital"},
  {"name": "gig oca robles seamen?s hospital davao"},
  {"name": "gigmoto district hospital"},
  {"name": "gilberto o. teodoro memorial hospital"},
  {"name": "gingoog sanitarium and hospital"},
  {"name": "glan medicare community hospital"},
  {"name": "global care medical center of bay, inc."},
  {"name": "global care medical center of canlubang, inc."},
  {"name": "global medical center of laguna, inc."},
  {"name": "gmf hospital"},
  {"name": "god's will medical hospital"},
  {"name": "golden gate batangas hospital, inc. (formerly golden gate ge"},
  {"name": "gonzales general hospital"},
  {"name": "gonzales maranan med. ctr.,inc. guihing satellite"},
  {"name": "gonzales maranan medical center, inc."},
  {"name": "gonzales medical and childrens hospital"},
  {"name": "gonzales medical-surgical and birthing clinic"},
  {"name": "good news clinic and hospital"},
  {"name": "good shepherd hospital of panabo city, inc."},
  {"name": "gov. roque b. ablan sr. memorial hospital"},
  {"name": "gov. valeriano gatuslao memorial district hospital"},
  {"name": "gov. william (billy) villegas memorial hospital"},
  {"name": "governor celestino gallares memorial hospital"},
  {"name": "governor faustino n. dy sr. memorial hospital"},
  {"name": "governor niel d. tupas, sr. district hospital"},
  {"name": "gozo community hospital"},
  {"name": "grace general hospital, inc."},
  {"name": "grace mission hospital"},
  {"name": "graman medical and maternity hospital, inc."},
  {"name": "green city medical center"},
  {"name": "greg hospital-sariaya, inc."},
  {"name": "gregorio del pilar district hospital"},
  {"name": "gregorio matas district hospital"},
  {"name": "gregorio t. lluch memorial hospital"},
  {"name": "grospe polymedic"},
  {"name": "grupo medico de dios inc."},
  {"name": "guardiano maternity and children clinic and hospital"},
  {"name": "guba community hospital"},
  {"name": "gubatan clinic"},
  {"name": "guiguinto polymedic hospital, inc. (formerly bulacan polymed"},
  {"name": "guimba community hospital"},
  {"name": "guimba district hospital"},
  {"name": "guimba general hospital, inc,"},
  {"name": "guinayangan medicare community hospital"},
  {"name": "guindulungan doctors"},
  {"name": "gumaca district hospital"},
  {"name": "h-vill hospital"},
  {"name": "h.m. corachea general hospital"},
  {"name": "happy valley community hospital"},
  {"name": "havilah polymedic"},
  {"name": "healthserv los ba?os medical center"},
  {"name": "heart of jesus hospital"},
  {"name": "heramil hospital"},
  {"name": "hibo-francisco hospital"},
  {"name": "hijrah infirmary"},
  {"name": "hilongos district hospital"},
  {"name": "hinatuan district hospital"},
  {"name": "hinigaran medical clinic"},
  {"name": "hinunangan community hospital"},
  {"name": "hofilena hospital"},
  {"name": "holistic care general hospital"},
  {"name": "holy child colleges of butuan hospital co."},
  {"name": "holy child hospital"},
  {"name": "holy child medical city inc."},
  {"name": "holy family hospital"},
  {"name": "holy family medical center, inc."},
  {"name": "holy infant hospital of tuguegarao inc."},
  {"name": "holy mary women and children's hospital"},
  {"name": "holy mother of mercy hospital (former bacolod our mother of"},
  {"name": "holy name university medical center, inc."},
  {"name": "holy nazarene clinic and hospital"},
  {"name": "holy rosary hospital"},
  {"name": "holy rosary of cabuyao hospital, inc."},
  {"name": "holy spirit community hospital of davao, inc."},
  {"name": "holy trinity general hospital"},
  {"name": "holy trinity hospital"},
  {"name": "holy trinity medical clinic"},
  {"name": "holylife hospital"},
  {"name": "horizon medical clinic"},
  {"name": "hospital de zamboanga inc."},
  {"name": "hospital of the holy cross"},
  {"name": "hospital of the infant jesus medical center (formerly: chile"},
  {"name": "howard hubbard memorial hospital"},
  {"name": "htc specialty clinic & diagnostic laboratory"},
  {"name": "hungduan municipal hospital"},
  {"name": "ibajay district hospital"},
  {"name": "igacos general hospital, inc."},
  {"name": "ignacio lacson arroyo sr. memorial district hospital"},
  {"name": "iligan medical center hospital"},
  {"name": "ilocos sur cooperative medical mission group and hospital"},
  {"name": "ilocos sur district hospital - magsingal"},
  {"name": "ilocos sur district hospital - narvacan"},
  {"name": "ilocos sur district hospital - salcedo"},
  {"name": "ilocos sur district hospital - santa lucia"},
  {"name": "ilocos sur district hospital - sinait"},
  {"name": "ilocos sur district hospital - tagudin"},
  {"name": "ilocos sur district hospital-bessang pass cervantes"},
  {"name": "ilocos sur provincial hospital gabriela silang"},
  {"name": "ilocos training and regional medical center"},
  {"name": "iloilo doctors? hospital, incorporated"},
  {"name": "iloilo mission hospital, inc."},
  {"name": "iloilo provincial hospital"},
  {"name": "immaculate concepcion hospital of san pablo city, inc."},
  {"name": "immaculate concepcion polyclinic and hospital inc"},
  {"name": "immaculate conception clinic & hospital"},
  {"name": "immaculate conception health center"},
  {"name": "immaculate conception medical center of central luzon, inc."},
  {"name": "immaculate conception medical clinic"},
  {"name": "immaculate heart of mary hospital, inc."},
  {"name": "imus family hospital,inc."},
  {"name": "inapoy community primary hospital"},
  {"name": "indigineous peoples hospital foundation of the diocese of ba"},
  {"name": "infante hospital management corporation"},
  {"name": "integrated city health office"},
  {"name": "ipil doctor's hospital"},
  {"name": "irosin district hospital"},
  {"name": "irosin general hospital, inc."},
  {"name": "isaac and catalina medical center"},
  {"name": "isaac t. robillo memorial hospital"},
  {"name": "isabel emergency hospital"},
  {"name": "isabela doctors general hospital"},
  {"name": "isabela south specialists hospital, inc."},
  {"name": "isabela united doctors medical center, inc."},
  {"name": "isiah medical center"},
  {"name": "isidro kintanar memorial hospital"},
  {"name": "isidro m. olan sr. memorial clinic and hospital inc."},
  {"name": "isip general hospital"},
  {"name": "isulan doctors specialist center, inc."},
  {"name": "itbayat district hospital"},
  {"name": "itogon district hospital"},
  {"name": "j. cabahug hospital"},
  {"name": "j.p. sioson general hospital and colleges, inc"},
  {"name": "j.r. borja general hospital"},
  {"name": "ja alegre med.  clinic & hosp."},
  {"name": "jabez medical center"},
  {"name": "jabonga community infirmary"},
  {"name": "jabonga municipal hospital"},
  {"name": "jaime b. berces memorial hospital"},
  {"name": "jamelarin hospital"},
  {"name": "james l. gordon memorial hospital"},
  {"name": "januaria marcial  memorial hospital"},
  {"name": "jasaan municipal hospital"},
  {"name": "javier municipal infirmary"},
  {"name": "javonillo hospital, inc."},
  {"name": "jecsons medical center"},
  {"name": "jesus healing hands infirmary inc."},
  {"name": "jesus immaculate concepcion hospital"},
  {"name": "jesus m. colmenares district hospital"},
  {"name": "jesus nazarene general hospital"},
  {"name": "jesus the good shepherd hospital"},
  {"name": "jimenez medicare community hospital"},
  {"name": "jnral family corporation hospital"},
  {"name": "john mark villanueva medical clinic"},
  {"name": "jongno east medical center, inc."},
  {"name": "jose b. lingad memorial regional hospital"},
  {"name": "jose c. payumo jr. memorial hospital"},
  {"name": "jose j. golingay gen. hosp., inc."},
  {"name": "jose panganiban primary hospital service cooperative"},
  {"name": "jose r. reyes memorial medical center"},
  {"name": "jose songco lapid district hospital"},
  {"name": "josefina belmonte duran memorial district hospital"},
  {"name": "jowell general hospital"},
  {"name": "juan b. dosado memorial hospital"},
  {"name": "juan m. alberto memorial district hospital"},
  {"name": "juan m. duyan memorial district hospital"},
  {"name": "juan s. alano memorial hospital"},
  {"name": "judge celestino guerrero memorial hospital"},
  {"name": "julio cardinal rosales memorial hospital"},
  {"name": "justice calixto o. zaldivar memorial hospital"},
  {"name": "justice jose abad santos general hospital"},
  {"name": "juvelo family clinic"},
  {"name": "jvf clinic and lying-in memorial hospital"},
  {"name": "kabacan medical specialist, inc."},
  {"name": "kabacan polymedic cooperative hospital"},
  {"name": "kabankalan city hospital"},
  {"name": "kabasalan genral hospital"},
  {"name": "kairos maternity and general hospital"},
  {"name": "kalinga district hospital"},
  {"name": "kalinga provincial hospital"},
  {"name": "kalinga-gabriela mija kim medical center"},
  {"name": "kalumboyan community primary hospital"},
  {"name": "kananga municipal hospital"},
  {"name": "kapangan medicare and community hospital"},
  {"name": "kapatagan medical clinic"},
  {"name": "kapatagan provincial hospital"},
  {"name": "karmelli clinic and hospital"},
  {"name": "karmelli clinic and hospital pinili inc."},
  {"name": "kasibu municipal hospital"},
  {"name": "kauswagan provincial hospital"},
  {"name": "kawit kalayaan hospital"},
  {"name": "kidapawan city hospital"},
  {"name": "kidapawan doctors? hospital, inc."},
  {"name": "kidapawan medical specialists center, inc."},
  {"name": "kitcharao district hospital"},
  {"name": "kolambugan provincial hospital"},
  {"name": "kuta cesar l. sang-an station hospital"},
  {"name": "la consolacion university general hospital"},
  {"name": "la paz district hospital"},
  {"name": "la paz medicare and community hospital"},
  {"name": "la paz municipal hospital"},
  {"name": "la union medical center"},
  {"name": "la union medical diagnostic center and hospital"},
  {"name": "la vi?a general hospital, inc."},
  {"name": "labason district hospital"},
  {"name": "labella hospital"},
  {"name": "labo district hospital"},
  {"name": "labrador municipal hospital"},
  {"name": "labuan general hospital"},
  {"name": "lady of lourdes hospital of caybiga, inc."},
  {"name": "laguna doctors hospital, inc."},
  {"name": "laguna holy family hospital"},
  {"name": "laguna medical center"},
  {"name": "laguna provincial hospital - bay district hospital"},
  {"name": "laguna provincial hospital - gen. j. cailles memorial distri"},
  {"name": "laguna provincial hospital - luisiana district hospital"},
  {"name": "laguna provincial hospital - majayjay medicare hospital"},
  {"name": "laguna provincial hospital - nagcarlan district hospital"},
  {"name": "laguna provincial hospital-san pablo city district hospital"},
  {"name": "laguna provincial hospital-san pedro district hospital"},
  {"name": "lambayong district hospital"},
  {"name": "lanao del norte provincial hospital"},
  {"name": "lanceta medical hospital"},
  {"name": "landero clinic and hospital"},
  {"name": "languyan municipal hospital"},
  {"name": "laoag city general hospital"},
  {"name": "lapu-lapu city hospital"},
  {"name": "lariosa clinic and hospital"},
  {"name": "las nieves municipal hospital"},
  {"name": "las pi?as city medical center, inc."},
  {"name": "las pi?as doctors hospital, inc."},
  {"name": "las pi?as general hospital & satellite trauma center"},
  {"name": "lasam district hospital"},
  {"name": "laurel memorial district hospital"},
  {"name": "laxamana pediatric clinic"},
  {"name": "lazi medicare community hospital"},
  {"name": "lb cruel medical clinic"},
  {"name": "lebak family doctor's hospital"},
  {"name": "legazpi city hospital"},
  {"name": "lemery doctors medical center"},
  {"name": "leon d. hernandez memorial hospital, inc."},
  {"name": "leona o. lim memorial hospital"},
  {"name": "leonardo b. manabat sr. hospital, inc."},
  {"name": "leoncio general hospital"},
  {"name": "lepanto consolidated mining company hospital"},
  {"name": "leyte baptist hospital incorporated"},
  {"name": "leyte provincial hospital"},
  {"name": "lianga district hospital"},
  {"name": "libacao municipal infirmary"},
  {"name": "libmanan district hospital"},
  {"name": "lide pasar hospital"},
  {"name": "liloan community hospital"},
  {"name": "liloy integrated health district hospital"},
  {"name": "lim community hospital"},
  {"name": "lingap general hospital"},
  {"name": "lingayen district hospital"},
  {"name": "lingig community hospital"},
  {"name": "lipa city district hospital"},
  {"name": "lipa medix medical center"},
  {"name": "lipunan hospital"},
  {"name": "little angels medical hospital"},
  {"name": "living hope hospital, inc"},
  {"name": "liwag medical clinic, inc."},
  {"name": "lizaso hospital"},
  {"name": "llorente municipal hospital"},
  {"name": "lobo municipal hospital"},
  {"name": "lopez district farmers hospital, inc."},
  {"name": "lopez family clinic and hospital"},
  {"name": "lopez saint jude general hospital corp."},
  {"name": "lorenzo d. zayco district hospital"},
  {"name": "lorenzo tan multi-purpose cooperative hospital"},
  {"name": "loreto district hospital"},
  {"name": "loreto municipal hospital"},
  {"name": "lorma medical center, inc."},
  {"name": "los ba?os doctors hospital and medical center, incorporated"},
  {"name": "lourdes hospital"},
  {"name": "loving mother general hospital and diagnostic center, inc."},
  {"name": "lt. tidang memorial hospital"},
  {"name": "lu clinic and hospital"},
  {"name": "lubang district hospital"},
  {"name": "lucas-paguila medical clinic and hospital"},
  {"name": "lucban mmg hospital"},
  {"name": "lucena mmg general hospital"},
  {"name": "lucena united doctors incorporated (formerly: lucena united"},
  {"name": "ludovice general hospital"},
  {"name": "luis hora memorial regional hospital"},
  {"name": "lumbis rances general hospital"},
  {"name": "luna goco medical center"},
  {"name": "lung center of the philippines"},
  {"name": "lutheran hospital incorporated"},
  {"name": "luz-sikatuna community primary hospital"},
  {"name": "luzon medical center, inc."},
  {"name": "lyceum of aparri hospital"},
  {"name": "m. nape?as multispecialty hospital"},
  {"name": "m. simon hospital & pharmacy"},
  {"name": "m. v. gallego cabanatuan city general hospital"},
  {"name": "m.s. magbitang ospital ng san ildefonso"},
  {"name": "m.v. santiago medical center"},
  {"name": "m.v. santiago medical center - fcie branch"},
  {"name": "maasim municipal hospital"},
  {"name": "maasin maternity & children hospital"},
  {"name": "mabalacat district hospital"},
  {"name": "mabama doctors' hospital"},
  {"name": "mabinay medicare community hospital"},
  {"name": "mabini general hospital"},
  {"name": "mactan doctors? hospital, inc."},
  {"name": "maddela district hospital"},
  {"name": "madonna and child hospital"},
  {"name": "madonna medical center"},
  {"name": "madrid district hospital"},
  {"name": "magallanes medicare community hospital"},
  {"name": "magpoc maternity hospital, inc."},
  {"name": "magrina clinic and hospital"},
  {"name": "magsaysay memorial district hospital"},
  {"name": "magtabog general hospital"},
  {"name": "maguindanao provincial hospital"},
  {"name": "mahal na virgen maria santo rosario district hospital"},
  {"name": "mahayag district hospital"},
  {"name": "maheseco multipurpose cooperative"},
  {"name": "mainit medicare community hospital"},
  {"name": "maitum municipal hospital"},
  {"name": "major danilo atienza air base hospital"},
  {"name": "makati medical center"},
  {"name": "makilala medical specialist hospital, inc."},
  {"name": "makilala midway hospital,inc."},
  {"name": "malangas emergency infirmary"},
  {"name": "malay municipal hospital"},
  {"name": "malaybalay medical hospital care"},
  {"name": "malaybalay polymedic general hospital, inc."},
  {"name": "malimono district hospital"},
  {"name": "malipayon district hospital"},
  {"name": "malita district hospital"},
  {"name": "malolos maternity hospital and eye center"},
  {"name": "malolos san vicente hospital"},
  {"name": "malta medical center, inc."},
  {"name": "malungon municipal hospital"},
  {"name": "mama rachels hospital of mercy, inc."},
  {"name": "mambusao district hospital"},
  {"name": "manangan clinic and hospital"},
  {"name": "manango hospital"},
  {"name": "manaoag community hospital"},
  {"name": "mandaluyong city medical center"},
  {"name": "mandaon medicare community hospital"},
  {"name": "mandaue city hospital"},
  {"name": "mangatarem district hospital"},
  {"name": "manila doctors hospital"},
  {"name": "manila east medical center"},
  {"name": "manila naval hospital"},
  {"name": "manito municipal hospital"},
  {"name": "manuel a. roxas district hospital"},
  {"name": "manuel hospital"},
  {"name": "manuel j. santos hospital"},
  {"name": "manupac doctors healthcare"},
  {"name": "mapandan community hospital"},
  {"name": "maraat medical hospital"},
  {"name": "maramag mediclinic hospital and laboratory"},
  {"name": "maranding community hospital"},
  {"name": "marcelo hospital of baliwag, inc."},
  {"name": "marcelo-padilla children?s and medical hospital corporation"},
  {"name": "margosatubig regional hospital"},
  {"name": "maria dulce p. fanlo med. clin."},
  {"name": "maria estrella general hospital, inc."},
  {"name": "maria l. eleazar memorial district hospital"},
  {"name": "maria reyna-xavier university hospital, inc."},
  {"name": "marian hospital of santa rosa inc."},
  {"name": "mariano jesus cuenco memorial hospital"},
  {"name": "mariano marcos memorial hospital and medical center"},
  {"name": "maribojoc community hospital"},
  {"name": "marihatag district hospital"},
  {"name": "marikina doctors hospital and medical center, inc."},
  {"name": "marikina st. vincent general hospital, inc."},
  {"name": "marikina valley medical center"},
  {"name": "marilao st. michael family hospital, inc."},
  {"name": "mariveles district hospital"},
  {"name": "markvim hospital"},
  {"name": "marpe' medical clinic and hosp., inc"},
  {"name": "marrero acop pediatric triage and hydration clinic"},
  {"name": "martin marasigan memorial hospital"},
  {"name": "martinez memorial hospital"},
  {"name": "mary chiles general hospital, inc."},
  {"name": "mary immaculate maternity and general hospital"},
  {"name": "mary johnston hospital, inc."},
  {"name": "mary mediatrix medical center, inc."},
  {"name": "marymount hospital, inc."},
  {"name": "masbate medical mission group hospital service cooperative"},
  {"name": "masbate provincial hospital"},
  {"name": "mataas na kahoy community hospital"},
  {"name": "matalam midway hospital, inc."},
  {"name": "matalom community hospital"},
  {"name": "mateo's diagnostic clinic and general hospital, inc."},
  {"name": "mateo-mabborang general hospital"},
  {"name": "matias clinic and hospital"},
  {"name": "matilde a. olivas district hospital"},
  {"name": "matnog medicare community hospital"},
  {"name": "matutes medical clinic & hospital"},
  {"name": "mauban district hospital"},
  {"name": "mawab med. clinic & hosp."},
  {"name": "mayor hilarion a. ramiro, sr., medical center"},
  {"name": "mayor joaquin macias memorial infirmary"},
  {"name": "mayoyao district hospital"},
  {"name": "mbp - blessed trinity general hospital"},
  {"name": "mcpc st therese of lisieux doctors hospital"},
  {"name": "mcu-fdt medical foundation hospital"},
  {"name": "medcore hospital, inc."},
  {"name": "medical center imus"},
  {"name": "medical center manila, inc."},
  {"name": "medical center muntinlupa, inc."},
  {"name": "medical center of digos cooperative hospital (mcdc)"},
  {"name": "medical center of taguig city, inc."},
  {"name": "medical center para?aque, inc."},
  {"name": "medical center western batangas"},
  {"name": "medical centrum dagupan"},
  {"name": "medical mission group hospital & health services cooperative"},
  {"name": "medical mission group hospital and health services cooperati"},
  {"name": "medical mission group hospital multipurpose cooperative of o"},
  {"name": "medical mission group of hosp and health service- bohol coop"},
  {"name": "medicus medical center corporation"},
  {"name": "medidas medical center inc."},
  {"name": "medina general hospital"},
  {"name": "medina hospital"},
  {"name": "melvery maternity and general hospital"},
  {"name": "mendero medical center, inc."},
  {"name": "mendoza general hospital"},
  {"name": "merceditas j. montilla district hospital"},
  {"name": "mercy community hospital, inc."},
  {"name": "metro antipolo hospital and medical center, inc."},
  {"name": "metro bacolod hospital and medical center"},
  {"name": "metro balayan medical center"},
  {"name": "metro davao medical and research center, inc."},
  {"name": "metro health specialists hospital, inc."},
  {"name": "metro iloilo hospital and medical center, inc"},
  {"name": "metro lemery medical center"},
  {"name": "metro lipa medical center"},
  {"name": "metro north medical center and hospital, inc."},
  {"name": "metro pagadian specialist hospital, inc."},
  {"name": "metro rizal doctors hospital and health services cooperative"},
  {"name": "metro san jose medical center"},
  {"name": "metro south medical center"},
  {"name": "metro vigan multi-purpose cooperative hospital"},
  {"name": "metropolitan medical center"},
  {"name": "metropolitan medical center-nasugbu"},
  {"name": "metropolitan polymedic community hospital, inc."},
  {"name": "mexico community hospital"},
  {"name": "meycauayan doctors hospital and medical center, inc."},
  {"name": "midsayap community doctors hospital"},
  {"name": "midsayap diagnostic center and hospital"},
  {"name": "midway hospital"},
  {"name": "miguel o. cabrera sr. memorial hospital, corp."},
  {"name": "milagros albano district hospital"},
  {"name": "mina de oro general hospital"},
  {"name": "mindalano specialist  hospital foundation inc."},
  {"name": "mindanao central sanitarium"},
  {"name": "mindanao doctors hospital and cancer center, inc."},
  {"name": "mindanao foundation for medical disaster preparedness and re"},
  {"name": "mindanao medical center"},
  {"name": "minglanilla district hospital"},
  {"name": "miranda family hospital"},
  {"name": "misamis occidental provincial hospital"},
  {"name": "misamis oriental provincial hospital - balingasag"},
  {"name": "misamis oriental provincial hospital - claveria"},
  {"name": "misamis oriental provincial hospital - gingoog"},
  {"name": "misamis oriental provincial hospital - initao"},
  {"name": "misamis oriental provincial hospital - magsaysay"},
  {"name": "misamis oriental provincial hospital - talisayan"},
  {"name": "misamis oriental provincial hospital- manticao"},
  {"name": "misamis university medical center"},
  {"name": "mission hospital"},
  {"name": "mlang district hospital"},
  {"name": "mlang good samaritan hospital"},
  {"name": "mlang polymedic hospital,inc"},
  {"name": "mlang specialists medical center (msmc), inc."},
  {"name": "mmghhsp cooperati ve hospital"},
  {"name": "molino doctors hospital"},
  {"name": "moorehouse mission hosp."},
  {"name": "morong doctors hospital"},
  {"name": "mother and child hospital"},
  {"name": "mother of mercy hospital-tacloban, inc."},
  {"name": "mother teresa of calcutta medical center"},
  {"name": "mount carmel diocesan general hospital"},
  {"name": "mount of blessings hospital"},
  {"name": "mt. carmel hospital medical center of bulacan corporation"},
  {"name": "n.l. villa memorial medical center"},
  {"name": "nabilog community primary hospital"},
  {"name": "nabunturan doctors hosp., inc."},
  {"name": "naga city hospital"},
  {"name": "naguilian district hospital"},
  {"name": "naic doctors hospital, inc."},
  {"name": "naic medicare hospital"},
  {"name": "narra municipal hospital"},
  {"name": "nasipit district hospital"},
  {"name": "national center for mental health"},
  {"name": "national children?s hospital"},
  {"name": "national kidney and transplant institute"},
  {"name": "natonin community hospital"},
  {"name": "naujan municipal hospital"},
  {"name": "navotas city hospital"},
  {"name": "nazarenus college and hospital foundation, inc."},
  {"name": "nazareth general hospital, inc."},
  {"name": "negros oriental provincial hospital"},
  {"name": "new bulan st. jude medical clinic"},
  {"name": "new lucena polytechnic college medical clinic and hospital"},
  {"name": "new sinai mdi hospital"},
  {"name": "nicc doctors hospital"},
  {"name": "nodado general hospital"},
  {"name": "norala district hospital"},
  {"name": "north caloocan doctors hospital"},
  {"name": "northern benguet district hospital"},
  {"name": "northern cagayan district hospital"},
  {"name": "northern luzon adventist hospital"},
  {"name": "northern mindanao medical center"},
  {"name": "northern palawan provincial hospital"},
  {"name": "northern samar provincial hospital"},
  {"name": "northside doctors hospital"},
  {"name": "northwestern leyte district hospital"},
  {"name": "norzagaray municipal hospital"},
  {"name": "notre dame de chartres hospital"},
  {"name": "notre dame hospital and school of midwifery, inc."},
  {"name": "novaliches district hospital"},
  {"name": "novaliches general hospital"},
  {"name": "nuestra senora de piat district hospital"},
  {"name": "nuestro espiritu medical-surgical and diagnostic clinic"},
  {"name": "nuestro se?or sto. ni?o hospital, inc."},
  {"name": "nueva ecija doctors? hospital, inc."},
  {"name": "nueva ecija good samaritan health system, inc."},
  {"name": "nueva ecija good samaritan health system, inc. (ext.)"},
  {"name": "nueva ecija medics hospital"},
  {"name": "nueva valencia district hospital"},
  {"name": "nueva vizcaya provincial hospital"},
  {"name": "ocampo municipal hospital"},
  {"name": "occidental mindoro provincial hospital"},
  {"name": "ocw general hospital"},
  {"name": "ofelia l. mendoza maternity and general hospital"},
  {"name": "olegario general hospital"},
  {"name": "olivarez general hospital"},
  {"name": "olutanga municipal hospital"},
  {"name": "orani district hospital"},
  {"name": "oras district hospital"},
  {"name": "oras doctors hospital"},
  {"name": "ordonez medical hospital"},
  {"name": "oriental mindoro central district hospital"},
  {"name": "oriental mindoro provincial hospital"},
  {"name": "oriental mindoro southern district hospital"},
  {"name": "orion saint michael hospital"},
  {"name": "ormoc district hospital"},
  {"name": "ormoc doctors? hospital, inc."},
  {"name": "ormoc maternity & children's hospital inc"},
  {"name": "oroquieta community hospital"},
  {"name": "ortigas hospital and healthcare center, inc."},
  {"name": "oslob district hospital"},
  {"name": "ospital ng biñan"},
  {"name": "ospital ng cabuyao"},
  {"name": "ospital ng calaca"},
  {"name": "ospital ng guiguinto"},
  {"name": "ospital ng imus"},
  {"name": "ospital ng kabataan ng dipolog, inc"},
  {"name": "ospital ng lipa"},
  {"name": "ospital ng lungsod ng san jose"},
  {"name": "ospital ng lungsod ng san jose del monte"},
  {"name": "ospital ng makati"},
  {"name": "ospital ng malabon"},
  {"name": "ospital ng maynila medical center"},
  {"name": "ospital ng muntinlupa"},
  {"name": "ospital ng nasugbu"},
  {"name": "ospital ng palawan"},
  {"name": "ospital ng parañaque"},
  {"name": "ospital ng sampaloc"},
  {"name": "ospital ng santa cruz"},
  {"name": "ospital ng tagaytay"},
  {"name": "ospital ng tondo"},
  {"name": "ospital ning capas"},
  {"name": "our lady mediatrix hospital"},
  {"name": "our lady of caysasay medical center, inc."},
  {"name": "our lady of fatima hospital"},
  {"name": "our lady of grace hospital inc."},
  {"name": "our lady of guadalupe hospital"},
  {"name": "our lady of hope medical clinic & hosp."},
  {"name": "our lady of lourdes hospital"},
  {"name": "our lady of lourdes infirmary"},
  {"name": "our lady of lourdes international medical center, inc."},
  {"name": "our lady of mercy general hospital, inc."},
  {"name": "our lady of mt. carmel medical center, inc."},
  {"name": "our lady of mt. carmel medical center-clark, inc."},
  {"name": "our lady of peace medical clinic"},
  {"name": "our lady of porziuncola hospital, inc."},
  {"name": "our lady of rosary hospital, inc."},
  {"name": "our lady of rule maternity and general hospital"},
  {"name": "our lady of the pillar medical center"},
  {"name": "our lady of the way medical and pediatric clinic"},
  {"name": "our savior hospital, inc."},
  {"name": "owwa misamis oriental provincial hospital- alubijid"},
  {"name": "ozamis city saint joseph general hospital"},
  {"name": "p. gonzales memorial hospital, inc."},
  {"name": "pacific global medical center, inc."},
  {"name": "pacuan community primary hospital"},
  {"name": "padre burgos community hospital"},
  {"name": "padre pio maternity and medical hospital, inc."},
  {"name": "padron - tibio medical clinic"},
  {"name": "paete general hospital"},
  {"name": "pag-asa hospital"},
  {"name": "pagadian city medical center"},
  {"name": "pagadian doctors hospital"},
  {"name": "pagamutan ng dasmari?as"},
  {"name": "pagamutang bayan ng carmona"},
  {"name": "pagsanjan medical clinic and general hospital"},
  {"name": "palanan station hospital"},
  {"name": "palawan baptist hospital"},
  {"name": "palawan medical mission group multipurpose cooperative (pmmg"},
  {"name": "palma-malaluan hospital"},
  {"name": "paluan community hospital"},
  {"name": "pamana medical center"},
  {"name": "pampanga eent and general hospital"},
  {"name": "pampanga medical specialist hospital, inc."},
  {"name": "pampanga premier medical center inc."},
  {"name": "panabo polymedic hospital, inc."},
  {"name": "panamao district hospital"},
  {"name": "panay health care multi-purpose cooperative"},
  {"name": "pandan district hospital"},
  {"name": "pandi maternity and medical clinic"},
  {"name": "pangantucan doctors hospital corporation"},
  {"name": "pangantucan medical hospital"},
  {"name": "pangasinan doctors hospital"},
  {"name": "pangasinan provincial hospital"},
  {"name": "paniqui general hospital"},
  {"name": "panopdopan district hospital"},
  {"name": "pantaleon g. gotladera memorial hospital"},
  {"name": "pantao district hospital"},
  {"name": "paracelis district hospital"},
  {"name": "parang district hospital"},
  {"name": "paredes medical center and hospital"},
  {"name": "pasay city general hospital"},
  {"name": "pascual general hospital"},
  {"name": "pasig city children?s hospital ? child?s hope"},
  {"name": "pasig city general hospital"},
  {"name": "pasig doctors medical center inc."},
  {"name": "pathfinder estate hospital"},
  {"name": "paulina lim memorial hospital"},
  {"name": "pazzu medical clinic"},
  {"name": "pedro l. gindap municipal hospital"},
  {"name": "perpetual succor hospital and maternity inc."},
  {"name": "perpetual succour hospital of cebu, inc."},
  {"name": "peter paul medical center of candelaria, inc."},
  {"name": "philippine children?s medical center"},
  {"name": "philippine heart center"},
  {"name": "philippine orthopedic center"},
  {"name": "phillips memorial hospital"},
  {"name": "philsaga mining hospital"},
  {"name": "piddig district hospital"},
  {"name": "piedad medical clinic"},
  {"name": "pigcawayan doctors specialists hospitals, inc."},
  {"name": "pinamalayan doctors hospital"},
  {"name": "pinan district hospital"},
  {"name": "pineda-aquino general hosp"},
  {"name": "pines city doctors? hospital"},
  {"name": "pintuyan district hospital"},
  {"name": "pinukpuk district hospital"},
  {"name": "pio duran memorial district hospital"},
  {"name": "pira hospital"},
  {"name": "plaridel community hospital"},
  {"name": "plaridel infirmary (bulacan medical center annex)"},
  {"name": "pltc, inc. luis a. tiam medical center"},
  {"name": "pnp general hospital"},
  {"name": "pnp hospital region 13"},
  {"name": "pnp pro8 infirmary"},
  {"name": "pnp station hospital"},
  {"name": "police regional office 4a hospital"},
  {"name": "police regional office 6 primary health care hospital"},
  {"name": "polillo medicare hospital"},
  {"name": "polomolok municipal hospital"},
  {"name": "polymedic birthing and natal care"},
  {"name": "ponferrada polymedic hospital"},
  {"name": "pope john paul ii hospital and medical center inc."},
  {"name": "potia district hospital"},
  {"name": "pozorrubio community hospital"},
  {"name": "premiere general hospital of nueva ecija, baler aurora, inc."},
  {"name": "premiere medical center"},
  {"name": "pres. ramon magsaysay memorial hospital"},
  {"name": "pres. roxas prov'l community hosp."},
  {"name": "president carlos p. garcia municipal hospital"},
  {"name": "president diosdado macapagal district hospital"},
  {"name": "pri medical center"},
  {"name": "prieto diaz municipal hospital"},
  {"name": "prime global care medical center, inc."},
  {"name": "procare medical clinic and infirmary"},
  {"name": "prospero g. bello integrated community hospital"},
  {"name": "providence hospital, inc."},
  {"name": "providers multi-purpose cooperative medical center"},
  {"name": "pudpud polyclinic & specialty hospital"},
  {"name": "puerto community hospital"},
  {"name": "puerto galera urgent care clinic & diagnostic center"},
  {"name": "puyaoan general hospital"},
  {"name": "quali-life medical and lying-in clinic"},
  {"name": "qualimed health network"},
  {"name": "qualimed health network sjdm"},
  {"name": "qualimed health network sta. rosa"},
  {"name": "que medical clinic, lying-in and pharmacy"},
  {"name": "queen mary help of christian hospital inc."},
  {"name": "queen mary hospital"},
  {"name": "queensberry hospital"},
  {"name": "quezon city general hospital"},
  {"name": "quezon community infirmary"},
  {"name": "quezon institute"},
  {"name": "quezon medical center"},
  {"name": "quezon medicare hospital"},
  {"name": "quijano clinic and hospital, inc."},
  {"name": "quinapondan community hospital"},
  {"name": "quirino memorial medical center"},
  {"name": "quirino primary health care facility"},
  {"name": "quirino province medical center"},
  {"name": "r and l medical clinic"},
  {"name": "r de c galvez medical center"},
  {"name": "r.o. diagan cooperative hospital"},
  {"name": "r.s. clinic and hospital"},
  {"name": "rabara clinic and hospital"},
  {"name": "racelis-tiongson medical clinic"},
  {"name": "rafael lazatin memorial medical center"},
  {"name": "ragay district hospital"},
  {"name": "rakkk prophet medical center, inc."},
  {"name": "ralph edmund spencer foundation inc. hospital"},
  {"name": "ramirez bautista memorial hospital"},
  {"name": "ramiro community hospital"},
  {"name": "ramon d. duremdes district hospital"},
  {"name": "ramon maza sr. memorial district hospital"},
  {"name": "ramon tabiana memorial district hospital"},
  {"name": "ramos general hospital"},
  {"name": "ranada general hospital"},
  {"name": "ranao family medical clinic"},
  {"name": "rapu-rapu district hospital"},
  {"name": "rayos-valentin hospital, inc"},
  {"name": "razo medical hospital"},
  {"name": "recel medical clinic and hospital"},
  {"name": "recuenco general hospital, inc."},
  {"name": "region i medical center"},
  {"name": "region ii trauma and medical center      (veterans regional"},
  {"name": "regional health service 2 hospital"},
  {"name": "reina del cielo maternity and general hospital"},
  {"name": "renato umali reyes hospital of bongabong"},
  {"name": "renmar specialists' hospital"},
  {"name": "rep. pedro g. trono memorial hospital"},
  {"name": "research institute for tropical medicine"},
  {"name": "resonable hospital"},
  {"name": "retuerma general hospital"},
  {"name": "revelo medical clinic"},
  {"name": "rever medical center, inc."},
  {"name": "reyes ulep clinic and hospital"},
  {"name": "ricardo l. maningo memorial hospital"},
  {"name": "ricardo limso medical center, inc."},
  {"name": "ricardo p. rodriguez memorial hospital"},
  {"name": "ricardo p. rodriguez memorial hospital (annex specialty hosp"},
  {"name": "rico's hospital"},
  {"name": "ridon's st. jude medical center"},
  {"name": "rillera medical hospital"},
  {"name": "rivera medical center, inc."},
  {"name": "rizal medical center"},
  {"name": "rizal provincial hospital system - angono annex"},
  {"name": "rizal provincial hospital system - antipolo annex"},
  {"name": "rizal provincial hospital system - antipolo annex ii"},
  {"name": "rizal provincial hospital system - binangonan annex"},
  {"name": "rizal provincial hospital system - morong main"},
  {"name": "rmci satellite primary clinic"},
  {"name": "roa medical clinic"},
  {"name": "rodolfo morales med. clin."},
  {"name": "roel i. senador md memorial hospital"},
  {"name": "rogaciano m. mercado memorial hospital"},
  {"name": "roldan medical clinic and hospital"},
  {"name": "romana pangan district hospital"},
  {"name": "romblon district hospital"},
  {"name": "romblon provincial hospital"},
  {"name": "romel cruz hospital"},
  {"name": "romeo b. sibud country hopsital"},
  {"name": "romualdez-katiku community hosp."},
  {"name": "rosales chua pun memorial infirmary inc."},
  {"name": "rosales municipal infirmary unit"},
  {"name": "rosario district hospital"},
  {"name": "rosario maclang bautista general hospital"},
  {"name": "rosario memorial hospital of guagua, inc."},
  {"name": "rosario-trino medical clinic and diagnostic center"},
  {"name": "rosary of virgin mary hospital"},
  {"name": "rovillos hospital"},
  {"name": "roxas medicare hospital"},
  {"name": "roxas memorial provincial hospital"},
  {"name": "rtn foundation, inc. hospital"},
  {"name": "rugay general hospital, inc."},
  {"name": "s.s lumapas medical clinic"},
  {"name": "sabal hospital, inc."},
  {"name": "saballa-rosario hospital"},
  {"name": "sabater hospital"},
  {"name": "sacred heart hospital of malolos, inc."},
  {"name": "sacred heart medical center"},
  {"name": "sagnay infirmary"},
  {"name": "sagrada familia hospital"},
  {"name": "sagrado medical and children's clinic"},
  {"name": "saint andrea maternity and general hospital"},
  {"name": "saint anthony mother and child hospital"},
  {"name": "saint camillus de lellis general hospital"},
  {"name": "saint camillus maternity and polyclinic"},
  {"name": "saint gabriel medical center, inc."},
  {"name": "saint gabriel medical center, inc. (new)"},
  {"name": "saint joseph hospital of remedios,  inc."},
  {"name": "saint jude's hospital, inc."},
  {"name": "saint lawrence hospital"},
  {"name": "saint padre pio medical clinic"},
  {"name": "saint pascal de baylon hospital corporation"},
  {"name": "saint patrick?s hospital medical center"},
  {"name": "saint therese hospital"},
  {"name": "saint vincent de paul hospital"},
  {"name": "salcedo doctors hospital, inc"},
  {"name": "salomon-mangilet maternity and medical hospital"},
  {"name": "salubris inc."},
  {"name": "salug valley medical center"},
  {"name": "salvacion oppus y?iguez memorial provincial hospital"},
  {"name": "salvador general hospital"},
  {"name": "salvador r. encinas district hospital"},
  {"name": "salve regina general hospital inc."},
  {"name": "samar provincial hospital"},
  {"name": "sampaloc medicare community hospital"},
  {"name": "san andres municipal hospital"},
  {"name": "san antonio city of ilagan hospital"},
  {"name": "san antonio district hospital"},
  {"name": "san antonio medical center of lipa, inc."},
  {"name": "san carlos city hospital"},
  {"name": "san carlos doctors' hospital"},
  {"name": "san diego de alcala general hospital"},
  {"name": "san fernandino hospital"},
  {"name": "san francisco doctors hospital, inc."},
  {"name": "san francisco municipal hospital"},
  {"name": "san isidro hospital"},
  {"name": "san joaquin mother and child hospital"},
  {"name": "san jose city general hospital"},
  {"name": "san jose district hospital"},
  {"name": "san jose hospital and medical center, inc."},
  {"name": "san jose medicare community hospital"},
  {"name": "san juan de dios educational foundation, inc."},
  {"name": "san juan district hospital"},
  {"name": "san juan doctors hospital, inc."},
  {"name": "san juan general hospital"},
  {"name": "san juan medical center"},
  {"name": "san lazaro hospital"},
  {"name": "san lorenzo hospital health management co., inc."},
  {"name": "san lorenzo hospital health management company, inc."},
  {"name": "san lorenzo ruiz women's hospital"},
  {"name": "san luis district hospital"},
  {"name": "san marcelino district hospital"},
  {"name": "san mariano community hospital"},
  {"name": "san mateo doctors hospital, inc."},
  {"name": "san mateo integrated community hospital"},
  {"name": "san mateo multicare hospital, inc."},
  {"name": "san miguel community hospital"},
  {"name": "san miguel district hospital"},
  {"name": "san miguel hospital"},
  {"name": "san narciso municipal hospital"},
  {"name": "san pablo city general hospital"},
  {"name": "san pablo colleges medical center"},
  {"name": "san pablo doctors hospital"},
  {"name": "san pascual baylon maternity and general hospital"},
  {"name": "san pedro calungsod medical center, inc."},
  {"name": "san pedro doctors hospital, inc."},
  {"name": "san pedro hospital of davao city, inc."},
  {"name": "san pedro jose l. amante emergency hospital"},
  {"name": "san sebastian district hospital"},
  {"name": "san vicente district hospital"},
  {"name": "sanctissimo rosario general hospital"},
  {"name": "sandig medical clinic and hospital"},
  {"name": "santa cruz community hospital"},
  {"name": "santa cruz district hospital"},
  {"name": "santa cruz laguna polymedic, inc."},
  {"name": "santa marcela medicare and community hospital"},
  {"name": "santa romana yson memorial hospital"},
  {"name": "santa rosa community hospital"},
  {"name": "santana maternity and children's hospital, inc."},
  {"name": "santiago medical city (new)"},
  {"name": "santissima trinidad hospital"},
  {"name": "santissima trinidad hospital of daet"},
  {"name": "santo domingo district hospital"},
  {"name": "santo nino de casipit general hospital"},
  {"name": "santo rosario maternity and medical clinic"},
  {"name": "santo tomas general hospital"},
  {"name": "santos general hospital of malolos, inc."},
  {"name": "sara district hospital"},
  {"name": "sarangani healthcare facility"},
  {"name": "sarangani municipal hosp."},
  {"name": "saroma hospital"},
  {"name": "schistosomiasis hospital"},
  {"name": "sds medical center"},
  {"name": "se?or sto. ni?o hospital, inc."},
  {"name": "seamen?s hospital"},
  {"name": "seamen?s hospital-iloilo"},
  {"name": "sebaste community hospital"},
  {"name": "semirara mining and power corporation hospital"},
  {"name": "sen. gerardo roxas memorial district hospital"},
  {"name": "sen. ninoy aquino mun. hospital"},
  {"name": "señor tesoro hospital"},
  {"name": "siargao district hospital"},
  {"name": "sibuco municipal hospital"},
  {"name": "sibutad municipal hospital"},
  {"name": "sibuyan district hospital"},
  {"name": "silang doctors hospital"},
  {"name": "silang specialists medical center, inc."},
  {"name": "silva's clinic"},
  {"name": "simbulan sto. ni?o hospital"},
  {"name": "sinawilan clinic & hospital and hospital"},
  {"name": "sindangan district hospital"},
  {"name": "siniloan pioneer general hospital, inc"},
  {"name": "siocon district hospital"},
  {"name": "sipocot district hospital"},
  {"name": "siquijor provincial hospital"},
  {"name": "siruma municipal hospital"},
  {"name": "sjp infirmary diagnostic and pharmacy"},
  {"name": "skyline hospital and medical center"},
  {"name": "slu - hospital of the sacred heart"},
  {"name": "snh bustos corporation"},
  {"name": "socomedics medical center"},
  {"name": "socorro district hospital"},
  {"name": "socsargen county hospital"},
  {"name": "sogod district hospital"},
  {"name": "soler general hospital"},
  {"name": "soller general hospital, inc."},
  {"name": "somoso general hospital, inc."},
  {"name": "soriano-leyble medical and maternity hospital"},
  {"name": "sorilla medical and maternity clinic and hospital"},
  {"name": "sorsogon medical mission group hospital and health services"},
  {"name": "south bacolod general hospital and medical center, inc."},
  {"name": "south city hospital and medical center, inc."},
  {"name": "south cotabato provincial hospital"},
  {"name": "south davao med. specilaists hospital, inc."},
  {"name": "south superhighway medical center"},
  {"name": "south upi municipal hospital"},
  {"name": "southeast asian medical center, inc. (new)"},
  {"name": "southern isabela general hospital"},
  {"name": "southern palawan provincial hospital"},
  {"name": "southern philippines medical center"},
  {"name": "southwestern university medical center"},
  {"name": "specialist group hospital and trauma center"},
  {"name": "specialists' primary care of ilang, inc."},
  {"name": "st. andrew hospital"},
  {"name": "st. ann medical hospital"},
  {"name": "st. anne clinic"},
  {"name": "st. anne general hospital, inc."},
  {"name": "st. anthony college hospital"},
  {"name": "st. anthony medical center of marikina, inc."},
  {"name": "st. augustine hospital"},
  {"name": "st. benedict hospital of davao del sur, inc (new)"},
  {"name": "st. bernard infirmary and multi-specialty clinic, inc."},
  {"name": "st. camillus hosp of mati foundation, inc."},
  {"name": "st. camillus hospital"},
  {"name": "st. camillus medical center"},
  {"name": "st. catherine of alexandria foundation & medical center"},
  {"name": "st. christiana maternity hospital"},
  {"name": "st. claire hospital"},
  {"name": "st. clare?s medical center, inc."},
  {"name": "st. clement medical clinic"},
  {"name": "st. dominic medical center inc."},
  {"name": "st. elizabeth hospital, inc."},
  {"name": "st. felix medical hospital"},
  {"name": "st. frances cabrini medical center, inc."},
  {"name": "st. james hospital vqr medical foundation"},
  {"name": "st. james hospital, inc."},
  {"name": "st. john general hospital of buug, inc."},
  {"name": "st. john hospital, inc."},
  {"name": "st. john hospital, inc. (goa-naga city)"},
  {"name": "st. john medical and maternity clinic"},
  {"name": "st. john of the cross hospital"},
  {"name": "st. john paul ii medical center corp."},
  {"name": "st. john the baptist medical center, inc."},
  {"name": "st. joseph infirmary"},
  {"name": "st. joseph southern bukidnon hospital"},
  {"name": "st. jude family hospital"},
  {"name": "st. jude general hospital & medical center, inc."},
  {"name": "st. jude hospital"},
  {"name": "st. jude thaddeus general hospital (sjtgh)"},
  {"name": "st. jude's multispecialty hospital, inc."},
  {"name": "st. louis hospital"},
  {"name": "st. luke?s medical center"},
  {"name": "st. luke?s medical center - global city"},
  {"name": "st. magdalene hospital"},
  {"name": "st. martin de porres charity hospital"},
  {"name": "st. martin maternity and pediatric hospital"},
  {"name": "st. martin's mission hospital"},
  {"name": "st. mary's medical services, inc."},
  {"name": "st. marys maternity and childrens hospital, inc"},
  {"name": "st. mattheus medical hospital, inc."},
  {"name": "st. mazenod hospital, inc."},
  {"name": "st. michael general hospital"},
  {"name": "st. michael medical hospital"},
  {"name": "st. paul general hospital"},
  {"name": "st. paul hospital"},
  {"name": "st. paul hospital bulacan, inc."},
  {"name": "st. paul hospital cavite, inc."},
  {"name": "st. paul hospital of tuguegarao, inc."},
  {"name": "st. paul surigao university hospital, inc."},
  {"name": "st. paul?s hospital of iloilo, inc."},
  {"name": "st. peter and paul hospital of sorsogon, inc."},
  {"name": "st. peter claver hospital"},
  {"name": "st. raphael foundation & medical center, inc."},
  {"name": "st. scholastica's hospital"},
  {"name": "st. theresa wellness center"},
  {"name": "st. victoria hospital"},
  {"name": "st. vincent general hospital cebu, inc."},
  {"name": "st. vincent's medical clinic - hinundayan"},
  {"name": "sta. ana community hospital"},
  {"name": "sta. ana hospital"},
  {"name": "sta. cecilia medical center"},
  {"name": "sta. clara de montefalco medical center"},
  {"name": "sta. cruz hospital"},
  {"name": "sta. maria josefa hospital foundation, inc"},
  {"name": "sta. maria medical clinic & hospital"},
  {"name": "sta. maria village hospital, inc."},
  {"name": "sta. rosa hospital and medical center"},
  {"name": "sta. teresita general hospital"},
  {"name": "sta. teresita hospital, inc."},
  {"name": "sto. cristo milagroso hospital"},
  {"name": "sto. nino hospital"},
  {"name": "sto. niño hospital of philex mining corporation"},
  {"name": "sto. rosario hospital, inc."},
  {"name": "sts. francis and paul general hospital"},
  {"name": "sual primary care facility - infirmary"},
  {"name": "suero general hospital"},
  {"name": "sulop medical clinic"},
  {"name": "sultan kudarat district hospital"},
  {"name": "sultan kudarat doctors hospital, inc."},
  {"name": "sultan kudarat medical specialist center, inc."},
  {"name": "sultan kudarat provincial hospital"},
  {"name": "sultan naga dimaporo provincial hospital"},
  {"name": "sulu provincial hospital"},
  {"name": "sulu sanitarium"},
  {"name": "sumc foundation, inc."},
  {"name": "sumisip district hospital"},
  {"name": "sunga hospital"},
  {"name": "surallah community hospital"},
  {"name": "surigao del norte provincial hospital"},
  {"name": "surigao doctors' hospital, inc."},
  {"name": "surigao medical center inc."},
  {"name": "taal polymedic hospital and medical center"},
  {"name": "tabaco college hospital"},
  {"name": "tabango community hospital"},
  {"name": "tablas doctors hospital"},
  {"name": "tablas island district hospital"},
  {"name": "tacloban city hospital"},
  {"name": "tacurong city medical clinic, inc. (formerly tacurong city s"},
  {"name": "tadeco hospital"},
  {"name": "taft district hospital"},
  {"name": "tagaloguin-adona polymedic & diagnostic center, inc."},
  {"name": "tagaytay medical center, inc."},
  {"name": "tagbilaran community hospital corporation"},
  {"name": "tagbilaran maternity and children's hospital"},
  {"name": "tagig doctors hospital"},
  {"name": "tagoloan polymedic general hospital, inc."},
  {"name": "taguig-pateros district hospital"},
  {"name": "tagum doctors? hospital"},
  {"name": "talacogon district hospital"},
  {"name": "talisay district hospital"},
  {"name": "talon general hospital"},
  {"name": "tamola-tan medical hospital"},
  {"name": "tanay general hospital"},
  {"name": "tanchuling general hospital, inc."},
  {"name": "tanho medical clinic"},
  {"name": "tanque memorial clinic and hospital"},
  {"name": "tanza family general hospital and pharmacy"},
  {"name": "tapaz district hospital"},
  {"name": "tapul municipal hospital"},
  {"name": "tarangnan community hospital"},
  {"name": "tarlac provincial hospital"},
  {"name": "tayabas community hospital, inc."},
  {"name": "taytay doctors multi specialty hospital, inc."},
  {"name": "taytay maternity and child care center"},
  {"name": "tayug family hospital"},
  {"name": "teodoro b. galagar district hospital"},
  {"name": "teresita l. jalandoni provincial hospital"},
  {"name": "the black nazarene hospital, inc."},
  {"name": "the doctors? hospital, inc."},
  {"name": "the health centrum, inc."},
  {"name": "the lord's hospital"},
  {"name": "the medical city"},
  {"name": "the medical city - iloilo"},
  {"name": "the medical city clark, inc."},
  {"name": "the medical city pangasinan"},
  {"name": "the medical city south luzon"},
  {"name": "the ospa-farmers? medical center"},
  {"name": "the premier medical center"},
  {"name": "the ross mauricio memorial hospital"},
  {"name": "the st. theodore of tarsus hospital foundation, inc."},
  {"name": "tibungco doctors hospital"},
  {"name": "tiburcio b. aquino memorial hospital, inc."},
  {"name": "ticao district hospital"},
  {"name": "tigaon primary hospital"},
  {"name": "tiglao medical center foundation, inc."},
  {"name": "tinambac medicare community hospital"},
  {"name": "tinambac municipal hospital"},
  {"name": "tinoc district hospital"},
  {"name": "tobias feliciano faith hospital, inc."},
  {"name": "tojong inc. maternity and general hospital"},
  {"name": "toledo city general hospital"},
  {"name": "tolentino clinic and hospital"},
  {"name": "tolentino-gomez medical clinic"},
  {"name": "tomas-cacal medical clinic & hospital"},
  {"name": "tomboc - salayog hospital"},
  {"name": "tondo medical center"},
  {"name": "tongkil municipal hospital"},
  {"name": "torrijos municipal hospital"},
  {"name": "tricity medical center, inc."},
  {"name": "trifon saile memorial hospital"},
  {"name": "trinity woman and child center (the birthplace)"},
  {"name": "tuan ligaddung lipae memorial hospital"},
  {"name": "tuao district hospital"},
  {"name": "tubigon community hospital"},
  {"name": "tubod community hospital"},
  {"name": "tuburan district hospital"},
  {"name": "tucay multi-specialty hospital"},
  {"name": "tudela municipal hospital"},
  {"name": "tugon medical clinic and hospital"},
  {"name": "tuguegarao city people's general hospital"},
  {"name": "tumauini community hospital"},
  {"name": "tuy general hospital"},
  {"name": "uhbi-para?aque doctors hospital, inc."},
  {"name": "umali medical clinic"},
  {"name": "umingan community hospital"},
  {"name": "unayan municipal hospital"},
  {"name": "unciano colleges and general hospital, inc."},
  {"name": "unihealth para?aque hospital and medical center, inc."},
  {"name": "unihealth-southwoods hospital and medical center, inc."},
  {"name": "unisan medicare community hospital"},
  {"name": "united balagtas doctors hospital corporation"},
  {"name": "united candelaria doctors, inc."},
  {"name": "united doctor's hospital of tagum, inc."},
  {"name": "united doctors hospital of cotabato city, inc."},
  {"name": "united doctors hospital of kidapawan, inc."},
  {"name": "united doctors medical center"},
  {"name": "united doctors of st. camillus de lellis hospital"},
  {"name": "universidad de sta. isabel de naga, inc."},
  {"name": "universidad de zamboanga medical center"},
  {"name": "university health service"},
  {"name": "university of cebu medical center, inc."},
  {"name": "university of northern philippines hospital"},
  {"name": "university of perpetual help dalta medical center, inc."},
  {"name": "university of santo tomas (ust) - legazpi, inc. (formerly aq"},
  {"name": "university of santo tomas hospital"},
  {"name": "university of southern mindanao hospital"},
  {"name": "university of the east ramon magsaysay memorial medical cent"},
  {"name": "untalan general hospital"},
  {"name": "up health services"},
  {"name": "up-philippine general hospital"},
  {"name": "uph-dr. jose g. tamayo medical university foundation, inc."},
  {"name": "upper valley community hospital"},
  {"name": "urdaneta district hospital"},
  {"name": "urdaneta sacred heart hospital, inc."},
  {"name": "urology center of the philippines"},
  {"name": "v.l. makabali memorial hospital, inc."},
  {"name": "valderrama municipal hospital"},
  {"name": "valdez mother & child clinic & hosp."},
  {"name": "valencia medical hospital"},
  {"name": "valencia polymedic general hospital, inc."},
  {"name": "valenzuela citicare medical center-timog hilaga providence g"},
  {"name": "valenzuela city emergency hospital"},
  {"name": "valenzuela medical center"},
  {"name": "valera medical hospital"},
  {"name": "valladolid district hospital"},
  {"name": "velasquez medical clinic and hospital"},
  {"name": "velazco hospital"},
  {"name": "veterans memorial medical center"},
  {"name": "viacrucis infirmary"},
  {"name": "viacrucis medical hospital"},
  {"name": "vian family hospital ii"},
  {"name": "vicar francis hospital, inc."},
  {"name": "vice governor francisco ponce de leon memorial hospital"},
  {"name": "vicente gustilo district hospital"},
  {"name": "vicente l. peralta memorial district hospital"},
  {"name": "vicente mendiola center for health - infirmary"},
  {"name": "vicente sotto memorial medical center"},
  {"name": "victoriano luna medical center (formerly afp medical center)"},
  {"name": "viga district hospital"},
  {"name": "villaflor's clinic"},
  {"name": "villanueva-tanchuling maternity and general hospital incorpo"},
  {"name": "villarosa hospital, inc."},
  {"name": "villaviciosa medicare and community hospital"},
  {"name": "virgen milagrosa medical center"},
  {"name": "visayas community medical center, inc."},
  {"name": "visayas state university hospital"},
  {"name": "vt maternity hospital"},
  {"name": "wellserved infirmary and drugstore, inc."},
  {"name": "wesleyan university - philippines"},
  {"name": "west metro medical center"},
  {"name": "west visayas state university medical center"},
  {"name": "western kalinga district hospital"},
  {"name": "western leyte provincial hospital"},
  {"name": "western pangasinan district hospital"},
  {"name": "western visayas medical center"},
  {"name": "western visayas sanitarium"},
  {"name": "westlake medical center"},
  {"name": "westmin united doctors hospital co."},
  {"name": "wilfredo c. palma memorial hospital"},
  {"name": "women's children's community hospital inc."},
  {"name": "word of hope general hospital foundation, inc."},
  {"name": "world citi medical center, inc."},
  {"name": "ynares municipal hospital"},
  {"name": "zafra medical clinic & hosp."},
  {"name": "zambales medical mission group coop hospital"},
  {"name": "zamboanga city medical center"},
  {"name": "zamboanga del norte medical center"},
  {"name": "zamboanga del sur medical center"},
  {"name": "zamboanga doctors? hospital, inc."},
  {"name": "zamboanga peninsula medical center, inc."},
  {"name": "zamboanga puericulture center maternity lying-in hospital"},
  {"name": "zamboanga sibugay provincial hospital"},
  {"name": "zapanta general hospital"},
  {"name": "zapanta maternity & general hospital"},
  {"name": "zenon t. lagumbay memorial hospital"},
  {"name": "zmk doctors clinic & hospital"},
  {"name": "zone medical and intervention hospital, inc."}
];
