const List<String> REGION_LIST = [
  'BARMM',
  'CAR',
  'CARAGA',
  'NCR',
  'Region I: Ilocos Region',
  'Region II: Cagayan Valley',
  'Region III: Central Luzon',
  'Region IV-A: CALABARZON',
  'Region IV-B: MIMAROPA',
  'Region IX: Zamboanga Peninsula',
  'Region V: Bicol Region',
  'Region VI: Western Visayas',
  'Region VII: Central Visayas',
  'Region VIII: Eastern Visayas',
  'Region X: Northern Mindanao',
  'Region XI: Davao Region',
  'Region XII: SOCCSKSARGEN',
  'REPATRIATE',
];
