name: Flutter Test & Analyze

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

env:
  flutter_version: "1.20.2"
  java_version: "12.x"

jobs:
  test:
      runs-on: ubuntu-latest
      timeout-minutes: 5
      steps:
        - uses: actions/checkout@v1
        - uses: actions/setup-java@v1
          with:
            java-version: ${{ env.java_version }}
        - name: Cache Flutter dependencies
          uses: actions/cache@v1
          with:
            path: /opt/hostedtoolcache/flutter
            key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
        - uses: subosito/flutter-action@v1
          with:
            flutter-version: ${{ env.flutter_version }}
        - name: Install dependencies
          run: flutter pub get
        - name: Analyze
          run: flutter analyze
        - name: Test
          run: flutter test
